### ISSUE TITLE
math

### ISSUE THREAD

**Issue by holopyolo** [Moataz-Elmesmary/Data-Science-Roadmap#21]
I guess math must be in beginner page? At least before studying stats or probability

**Comment by Moataz-Elmesmary** [comment]
Stats and prob in beginner phase are just basics :) and when we reach a higher phase it gets more difficult in level.
if i put math at the beginning, i think people will just get bored or the may not continue>
also, imo, what is important is taking math before going through ML regardless of how i partitioned the roadmap in levels.
