### ISSUE TITLE
Broken YouTube Link in ( 11. SQL and DB ) 

### ISSUE THREAD

**Issue by A7med-Foly** [Moataz-Elmesmary/Data-Science-Roadmap#84]
### Broken Link

**Description:**
There is a broken link for the YouTube course. The link leads to a page that no longer exists.

**Details:**
- **Section:** ([Beginner](https://github.com/Moataz-Elmesmary/Data-Science-Roadmap?tab=readme-ov-file#-beginner-)) -> **11. SQL and DB** ]
- **Current Link:** (https://www.youtube.com/watch?v=QJHy89zMvj8&list=PLYpJKvLDuJhgMzOXRwUJ2_ZlVt3zSh8PA&index=2)
- **Suggested Action:** Please update the link to (https://www.youtube.com/playlist?list=PLSGEGD0dbMKrvd5ppnyFLm7q3xEH97T-t)

**Comment by Moataz-Elmesmary** [comment]
Hi Ahmed,
Thanks a lot for pointing out the broken link in this issue! I truly appreciate you taking the time to identify this and providing the correct link.
I'll be sure to update the repo with the accurate link you provided. This will greatly improve the clarity and value of this reference for everyone using it.
Thanks again for informing me. ❤️

**Comment by A7med-Foly** [comment]
Hi Moataz,

You're welcome! I'm glad I could help. Thank you for maintaining such a valuable resource for the community.
